safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /
url: http://localhost:4000

source:      ./input/html
destination: ./output
plugins:     ./input/html/_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:categories/:title.html