safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /
url: http://localhost:4000

source:      ./input
destination: ./output
plugins:     ./input/_plugins

future:      true
lsi:         false
pygments:    false
markdown:    kramdown
permalink:   /:categories/index.html
binarylink:  /:categories/:title.html
pagelink:    /:basename/index.html

languages:
  - ru
  - en

skippable:
  - introduction
  - about